type DispatchScriptOptions = {
  workers: number;
  commandTemplate?: string;
};

export function generateDispatchScript(options: DispatchScriptOptions): string {
  const { workers, commandTemplate } = options;
  const safeWorkers = Number.isFinite(workers) && workers > 0 ? Math.floor(workers) : 6;
  const escapedCommand = String(commandTemplate ?? "").replace(/'/g, "'\"'\"'");
  const useAutoDetect = !String(commandTemplate ?? "").trim();
  return [
    "#!/usr/bin/env bash",
    "# Agent Farm Dispatch",
    "# 默认行为：",
    "#   AGENT_FARM_GIT_WORKTREE=1 (默认) → 为每个任务创建独立 worktree",
    "#   AGENT_FARM_GIT_WORKTREE=0/false → --shared-workspace（关闭 worktree，使用共享目录）",
    "#   AGENT_FARM_AUTO_MERGE=1 (默认) → --auto-merge（任务完成后自动合并）",
    "#   AGENT_FARM_AUTO_MERGE=0/false → 禁用自动合并",
    `#   --workers 默认 ${safeWorkers}`,
    "",
    'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    'ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"',
    "",
    'PROFILE="$ROOT/.agent-farm/profile.env"',
    'if [[ -f "$PROFILE" ]]; then',
    "  set -a",
    "  # shellcheck disable=SC1090",
    '  source "$PROFILE"',
    "  set +a",
    "fi",
    'export PATH="$ROOT/node_modules/.bin:${PATH:-}"',
    "",
    'if [[ -f "$ROOT/dist/interfaces/cli/index.js" ]]; then',
    '  AGENT_FARM=(node "$ROOT/dist/interfaces/cli/index.js")',
    "elif command -v agent-farm >/dev/null 2>&1; then",
    "  AGENT_FARM=(agent-farm)",
    "else",
    '  echo "agent-farm: run \\"npm run build\\" in repo root, or install: npm i -g agent-farm-cli" >&2',
    "  exit 1",
    "fi",
    "",
    "# 与 project init --storage sqlite 一致，避免 shell 里残留 AGENT_FARM_STORAGE=jsonl",
    "export AGENT_FARM_STORAGE=sqlite",
    "",
    'PROMPT="${1:-}"',
    'if [ -z "$PROMPT" ]; then',
    '  echo "Usage: ./scripts/agent-farm-dispatch.sh \\"task prompt\\"" >&2',
    "  exit 1",
    "fi",
    "",
    'TASK_ID="task-$(date +%s)"',
    'DEDUPE_KEY="manual:${TASK_ID}"',
    "",
    ...(useAutoDetect
      ? [
          "# Auto-detect available executor in current environment",
          'if [[ -d "$ROOT/node_modules/opencode-ai" ]] || command -v opencode >/dev/null 2>&1; then',
          '  EXECUTOR_COMMAND_TEMPLATE=\'npx --prefix="$AGENT_FARM_WORKSPACE_ROOT" opencode-ai run --pure --dir "$AGENT_FARM_WORKSPACE" --dangerously-skip-permissions {prompt}\'',
          "elif command -v codex >/dev/null 2>&1; then",
          "  EXECUTOR_COMMAND_TEMPLATE='codex exec --skip-git-repo-check --dangerously-bypass-approvals-and-sandbox {prompt}'",
          "elif command -v claude >/dev/null 2>&1; then",
          "  EXECUTOR_COMMAND_TEMPLATE='claude -p {prompt} --output-format stream-json --verbose --dangerously-skip-permissions'",
          "else",
          '  echo "No supported executor found. Install one of: opencode, codex, claude" >&2',
          "  exit 1",
          "fi",
          "",
        ]
      : [`EXECUTOR_COMMAND_TEMPLATE='${escapedCommand}'`, ""]),
    '"${AGENT_FARM[@]}" queue add --prompt "$PROMPT" --task-id "$TASK_ID" --dedupe-key "$DEDUPE_KEY"',
    "",
    "WORKER_EXTRA=()",
    'if [[ "${AGENT_FARM_GIT_WORKTREE:-}" == "0" || "${AGENT_FARM_GIT_WORKTREE:-}" == "false" ]]; then',
    "  WORKER_EXTRA+=(--shared-workspace)",
    "fi",
    "# 多路 opencode-ai 时按任务隔离 OPENCODE_DB 并启用 JSON events（仅当模板包含 opencode-ai 时启用）",
    'if [[ "${EXECUTOR_COMMAND_TEMPLATE}" == *"opencode-ai"* ]]; then',
    "  WORKER_EXTRA+=(--isolate-opencode-db --opencode-json-events)",
    "# 多路 claude 时按任务隔离 CLAUDE_CONFIG_DIR 并启用 JSON events（仅当模板包含 claude 时启用）",
    'elif [[ "${EXECUTOR_COMMAND_TEMPLATE}" == *"claude"* ]]; then',
    "  WORKER_EXTRA+=(--isolate-claude-db --claude-json-events)",
    "fi",
    'if [[ "${AGENT_FARM_AUTO_MERGE:-}" != "0" && "${AGENT_FARM_AUTO_MERGE:-}" != "false" ]]; then',
    "  WORKER_EXTRA+=(--auto-merge)",
    "fi",
    "",
    '"${AGENT_FARM[@]}" worker \\',
    '  --workspace "$ROOT" \\',
    `  --workers ${safeWorkers} \\`,
    '  --command-template "${EXECUTOR_COMMAND_TEMPLATE}" \\',
    "  --lease-timeout-seconds 1800 \\",
    "  --poison-max-attempts 3 \\",
    '  "${WORKER_EXTRA[@]}"',
    "",
    '"${AGENT_FARM[@]}" insights',
    '"${AGENT_FARM[@]}" doctor',
    "",
  ].join("\n");
}
